apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: argus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/hjo3-cse40/Argus-worker:sha-5be249b2379dce4641935a24e73e98138ba79b1c
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: argus-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argus-secrets
                  key: DB_PASSWORD
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: argus-secrets
                  key: RABBITMQ_URL
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: argus-secrets
                  key: DISCORD_WEBHOOK_URL
