apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: argus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/hjo3-cse40/argus-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: API_UPSTREAM
              value: "http://api:8080"